/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GamePreferenceSurveyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "closeSurvey"
      | "createSurvey"
      | "getAdmin"
      | "getEncryptedTotals"
      | "getSurvey"
      | "getSurveyCount"
      | "hasResponded"
      | "protocolId"
      | "requestDecryptionAccess"
      | "submitResponse"
      | "surveyCount"
      | "surveys"
      | "transferAdmin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ResponseSubmitted"
      | "ResultsDecrypted"
      | "SurveyClosed"
      | "SurveyCreated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "closeSurvey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSurvey",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getAdmin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTotals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSurvey",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSurveyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasResponded",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestDecryptionAccess",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResponse",
    values: [
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "surveyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "surveys",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeSurvey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSurvey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTotals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSurvey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSurveyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasResponded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestDecryptionAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "surveyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "surveys", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
}

export namespace ResponseSubmittedEvent {
  export type InputTuple = [surveyId: BigNumberish, respondent: AddressLike];
  export type OutputTuple = [surveyId: bigint, respondent: string];
  export interface OutputObject {
    surveyId: bigint;
    respondent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultsDecryptedEvent {
  export type InputTuple = [
    surveyId: BigNumberish,
    pvp: BigNumberish,
    pve: BigNumberish,
    economic: BigNumberish,
    others: BigNumberish
  ];
  export type OutputTuple = [
    surveyId: bigint,
    pvp: bigint,
    pve: bigint,
    economic: bigint,
    others: bigint
  ];
  export interface OutputObject {
    surveyId: bigint;
    pvp: bigint;
    pve: bigint;
    economic: bigint;
    others: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SurveyClosedEvent {
  export type InputTuple = [surveyId: BigNumberish];
  export type OutputTuple = [surveyId: bigint];
  export interface OutputObject {
    surveyId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SurveyCreatedEvent {
  export type InputTuple = [
    surveyId: BigNumberish,
    title: string,
    deadline: BigNumberish
  ];
  export type OutputTuple = [surveyId: bigint, title: string, deadline: bigint];
  export interface OutputObject {
    surveyId: bigint;
    title: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GamePreferenceSurvey extends BaseContract {
  connect(runner?: ContractRunner | null): GamePreferenceSurvey;
  waitForDeployment(): Promise<this>;

  interface: GamePreferenceSurveyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  closeSurvey: TypedContractMethod<
    [_surveyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createSurvey: TypedContractMethod<
    [_title: string, _description: string, _durationInSeconds: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getAdmin: TypedContractMethod<[], [string], "view">;

  getEncryptedTotals: TypedContractMethod<
    [_surveyId: BigNumberish],
    [
      [string, string, string, string] & {
        pvp: string;
        pve: string;
        economic: string;
        others: string;
      }
    ],
    "view"
  >;

  getSurvey: TypedContractMethod<
    [_surveyId: BigNumberish],
    [
      [string, string, bigint, boolean, bigint] & {
        title: string;
        description: string;
        deadline: bigint;
        active: boolean;
        totalResponses: bigint;
      }
    ],
    "view"
  >;

  getSurveyCount: TypedContractMethod<[], [bigint], "view">;

  hasResponded: TypedContractMethod<
    [_surveyId: BigNumberish, _respondent: AddressLike],
    [boolean],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  requestDecryptionAccess: TypedContractMethod<
    [_surveyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitResponse: TypedContractMethod<
    [
      _surveyId: BigNumberish,
      inputPVP: BytesLike,
      inputPVE: BytesLike,
      inputEconomic: BytesLike,
      inputOthers: BytesLike,
      proofPVP: BytesLike,
      proofPVE: BytesLike,
      proofEconomic: BytesLike,
      proofOthers: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  surveyCount: TypedContractMethod<[], [bigint], "view">;

  surveys: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        boolean,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        title: string;
        description: string;
        deadline: bigint;
        active: boolean;
        totalPVP: string;
        totalPVE: string;
        totalEconomic: string;
        totalOthers: string;
        totalResponses: bigint;
      }
    ],
    "view"
  >;

  transferAdmin: TypedContractMethod<
    [_newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "closeSurvey"
  ): TypedContractMethod<[_surveyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createSurvey"
  ): TypedContractMethod<
    [_title: string, _description: string, _durationInSeconds: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedTotals"
  ): TypedContractMethod<
    [_surveyId: BigNumberish],
    [
      [string, string, string, string] & {
        pvp: string;
        pve: string;
        economic: string;
        others: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSurvey"
  ): TypedContractMethod<
    [_surveyId: BigNumberish],
    [
      [string, string, bigint, boolean, bigint] & {
        title: string;
        description: string;
        deadline: bigint;
        active: boolean;
        totalResponses: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSurveyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasResponded"
  ): TypedContractMethod<
    [_surveyId: BigNumberish, _respondent: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestDecryptionAccess"
  ): TypedContractMethod<[_surveyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitResponse"
  ): TypedContractMethod<
    [
      _surveyId: BigNumberish,
      inputPVP: BytesLike,
      inputPVE: BytesLike,
      inputEconomic: BytesLike,
      inputOthers: BytesLike,
      proofPVP: BytesLike,
      proofPVE: BytesLike,
      proofEconomic: BytesLike,
      proofOthers: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "surveyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "surveys"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        boolean,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        title: string;
        description: string;
        deadline: bigint;
        active: boolean;
        totalPVP: string;
        totalPVE: string;
        totalEconomic: string;
        totalOthers: string;
        totalResponses: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ResponseSubmitted"
  ): TypedContractEvent<
    ResponseSubmittedEvent.InputTuple,
    ResponseSubmittedEvent.OutputTuple,
    ResponseSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ResultsDecrypted"
  ): TypedContractEvent<
    ResultsDecryptedEvent.InputTuple,
    ResultsDecryptedEvent.OutputTuple,
    ResultsDecryptedEvent.OutputObject
  >;
  getEvent(
    key: "SurveyClosed"
  ): TypedContractEvent<
    SurveyClosedEvent.InputTuple,
    SurveyClosedEvent.OutputTuple,
    SurveyClosedEvent.OutputObject
  >;
  getEvent(
    key: "SurveyCreated"
  ): TypedContractEvent<
    SurveyCreatedEvent.InputTuple,
    SurveyCreatedEvent.OutputTuple,
    SurveyCreatedEvent.OutputObject
  >;

  filters: {
    "ResponseSubmitted(uint256,address)": TypedContractEvent<
      ResponseSubmittedEvent.InputTuple,
      ResponseSubmittedEvent.OutputTuple,
      ResponseSubmittedEvent.OutputObject
    >;
    ResponseSubmitted: TypedContractEvent<
      ResponseSubmittedEvent.InputTuple,
      ResponseSubmittedEvent.OutputTuple,
      ResponseSubmittedEvent.OutputObject
    >;

    "ResultsDecrypted(uint256,uint8,uint8,uint8,uint8)": TypedContractEvent<
      ResultsDecryptedEvent.InputTuple,
      ResultsDecryptedEvent.OutputTuple,
      ResultsDecryptedEvent.OutputObject
    >;
    ResultsDecrypted: TypedContractEvent<
      ResultsDecryptedEvent.InputTuple,
      ResultsDecryptedEvent.OutputTuple,
      ResultsDecryptedEvent.OutputObject
    >;

    "SurveyClosed(uint256)": TypedContractEvent<
      SurveyClosedEvent.InputTuple,
      SurveyClosedEvent.OutputTuple,
      SurveyClosedEvent.OutputObject
    >;
    SurveyClosed: TypedContractEvent<
      SurveyClosedEvent.InputTuple,
      SurveyClosedEvent.OutputTuple,
      SurveyClosedEvent.OutputObject
    >;

    "SurveyCreated(uint256,string,uint256)": TypedContractEvent<
      SurveyCreatedEvent.InputTuple,
      SurveyCreatedEvent.OutputTuple,
      SurveyCreatedEvent.OutputObject
    >;
    SurveyCreated: TypedContractEvent<
      SurveyCreatedEvent.InputTuple,
      SurveyCreatedEvent.OutputTuple,
      SurveyCreatedEvent.OutputObject
    >;
  };
}
