/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  SepoliaConfig,
  SepoliaConfigInterface,
} from "../../../../../@fhevm/solidity/config/ZamaConfig.sol/SepoliaConfig";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "protocolId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234610193575f6060610014610197565b8281528260208201528260408201520152731364cbbf2cdf5032c47d8226a6f6fbd2afcdacac6060610044610197565b73687820221192c5b662b25367f70076a37bc79b6c815273848b0066793bcc60346da1f49049357399b8d595602082015273a02cda4ca3a71d7c46997716f4283aa851c288126040820152015273687820221192c5b662b25367f70076a37bc79b6c60018060a01b03195f5160206102775f395f51905f525416175f5160206102775f395f51905f525573848b0066793bcc60346da1f49049357399b8d59560018060a01b03195f5160206102375f395f51905f525416175f5160206102375f395f51905f525573a02cda4ca3a71d7c46997716f4283aa851c2881260018060a01b03195f5160206102575f395f51905f525416175f5160206102575f395f51905f5255731364cbbf2cdf5032c47d8226a6f6fbd2afcdacac60018060a01b03195f5160206102175f395f51905f525416175f5160206102175f395f51905f5255604051604c90816101cb8239f35b5f80fd5b60405190608082016001600160401b038111838210176101b657604052565b634e487b7160e01b5f52604160045260245ffdfe60808060405260043610156011575f80fd5b5f3560e01c63da1f12ab146023575f80fd5b34603b575f366003190112603b578061271160209252f35b5f80fdfea164736f6c634300081b000a9e7b61f58c47dc699ac88507c4f5bb9f121c03808c5676a8078fe583e46497039e7b61f58c47dc699ac88507c4f5bb9f121c03808c5676a8078fe583e46497019e7b61f58c47dc699ac88507c4f5bb9f121c03808c5676a8078fe583e46497029e7b61f58c47dc699ac88507c4f5bb9f121c03808c5676a8078fe583e4649700";

type SepoliaConfigConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SepoliaConfigConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SepoliaConfig__factory extends ContractFactory {
  constructor(...args: SepoliaConfigConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SepoliaConfig & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SepoliaConfig__factory {
    return super.connect(runner) as SepoliaConfig__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SepoliaConfigInterface {
    return new Interface(_abi) as SepoliaConfigInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SepoliaConfig {
    return new Contract(address, _abi, runner) as unknown as SepoliaConfig;
  }
}
